### ISSUE TITLE
Unhandled exception za izmjenu jela/sastojka/radnika/popusta

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#11]
Komponenta:
Telefonske narudžbe

commit ID:
65782bcba236371e18665f563d95811ae5b18618

Opis problema:
Na svim tabovima button za izmjenu izazove izuzetak ukoliko 
nije odabrana nijedna stavka u tabeli.

Koraci za reproduciranje problema:
1. Login kao sef
2. Otici na tab Jelovnik/Sastojci/Korisnički računi/Popusti
3. Pritisnuti button Izmijeni jelo/Izmijeni sastojak/Izmijeni radnika/Izmijeni  popust

Screenshot:
http://prntscr.com/b4olvy

Dobijeni rezultat:
Unhandled exception

Očekivani rezultat:
Poruka da stavka nije odabrana

**Comment by admirah** [comment]
Popravljeno
