### ISSUE TITLE
Validacija jela nije ispravna: cijena moze biti negativna (ili 0)

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#12]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
Prilikom unosa jela, u bazu se spašavaju podaci koji nemaju smisla, tj. negativna cijena.

Koraci za reproduciranje problema:
1. Login kao sef
2. Otici na tab Jelovnik
3. Pritisnuti button Dodaj novo jelo
4. Unijeti tražene podatke (npr cijena = -100)
5. Pritisnuti button Završi uređivanje

Screenshot:
http://prntscr.com/b4os7x

Dobijeni rezultat:
Poruka da je jelo dodano

Očekivani rezultat:
Poruka da cijena mora biti veća od 0

**Comment by admirah** [comment]
Popravljeno
