### ISSUE TITLE
Unhandled exception za generisanje izvjestaja

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#13]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
Ukoliko pritisnemo button za generisanje izvještaja dolazi do bacanja izuzetka.

Koraci za reproduciranje problema:
1. Login kao sef
2. Odabrati izvještaj o vremenu isporuke narudžbi
3. Pritisnuti button Generiši izvještaj

Screenshot:
http://prntscr.com/b4olvy

Dobijeni rezultat:
Unhandled exception

Očekivani rezultat:
Generisan izvještaj

**Comment by admirah** [comment]
Popravljeno
