### ISSUE TITLE
Unos korisnika ciji username vec postoji

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#14]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
U bazu se unosi korisnik sa istim usernameom

Koraci za reproduciranje problema:
1. Login kao sef
2. Odabrati tab Korisnički računi
3. Pritisnuti button Dodaj radnika
4. Unijeti podatke radnika koji već postoji

Screenshot:
http://prntscr.com/b4qklr

Dobijeni rezultat:
Korisnik uspješno dodan

Očekivani rezultat:
Poruka o greški

**Comment by admirah** [comment]
Popravljeno
