### ISSUE TITLE
Nemogućnost logovanja (query did not return a unique result)

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#15]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
U bazi se nalazi korisnik sa istim username-om zbog čega se nije moguće logovati

Koraci za reproduciranje problema:
1. Login kao šef
2. Odabrati tab Korisnički računi
3. Pritisnuti button Dodaj radnika
4. Unijeti podatke radnika koji već postoji
5. Odjaviti se
6. Prijaviti se sa prije unesenim korisničkim podacima

Screenshot:
http://img.prntscr.com/img?url=http://i.imgur.com/rIrJavd.png

Dobijeni rezultat:
Nemogućnost prijave na aplikaciju

Očekivani rezultat:
Nepostojanje korisnika sa istim username-om

**Comment by admirah** [comment]
Problem je u biti u prethodnom bugu, mogucnost dodavanja vise korisnika sa istim usernameom, a ne u funkcionalnosti logovanja, ovdje se nema sta popravljati.
