### ISSUE TITLE
Neispravna validacija datuma kod dodavanja korisnika

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#16]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
Ukoliko je unešen neispravan datum, on se automatski prepravi na neki random datum i korisnik bude dodan bez ikakve prijave o greški.

Koraci za reproduciranje problema:
1. Login kao šef
2. Odabrati tab Korisnički računi
3. Pritisnuti button Dodaj radnika
4. Unijeti podatke radnika i datum npr. 22/22/1994
5. Korisnik uspješno dodan, a datum automatski ispravljen

Dobijeni rezultat:
Korisnik dodan bez obzira na pogrešan unos

Očekivani rezultat:
Poruka o unosu nevalidnog datuma

**Comment by admirah** [comment]
Popravljeno
