### ISSUE TITLE
Korisničke šifre nisu kriptovane

### ISSUE THREAD

**Issue by dzenana1** [SoftverInzenjeringETFSA/SI2015Tim5#17]
Komponenta:
Baza podataka

                                                                  Commit ID:
af1627f88296bb17f9944344a03585e0bb84ccef

                                                               Opis problema:
![bug2](https://cloud.githubusercontent.com/assets/11295655/15299454/c3e3833c-1ba4-11e6-9752-043f117501ca.png)
Šifre u bazi nisu kriptovane što dovodi do nesaglasnosti sa stavkom o sigurnosti u SRS-u.

![srssifre](https://cloud.githubusercontent.com/assets/11295655/15299544/28ef166a-1ba5-11e6-90de-8fd191b66e41.png)
  

                                                     Koraci za reproduciranje problema:
1.Otvoriti bazu podataka
2.Otvoriti tabelu  zaposlenik
3.Fokusirati se na polje password u tabeli
ili 
1.Otvoriti interfejs za šefa.
2.Pristupiti tab-u Korisnički računi
3.Fokusirati se na polje Lozinka u tabeli

![seflozinke](https://cloud.githubusercontent.com/assets/11295655/15300002/eb1ba43c-1ba6-11e6-84ab-41d226174b64.png)

                                                      Dobijeni rezultat:
Korisničke šifre u izvornom formatu

                                                    Očekivani rezultat
Kriptovane korisničke lozinke

**Comment by mathildaa** [comment]
Riješeno via 45f83a7ac9dc606b277798ffdb0f719c624b4fc7
