### ISSUE TITLE
Funkcionalni zahtjev iz SRSa "Pretraga jela po nazivu" ne postoji

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#18]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
U SRS-u piše da je potrebno da se korisnik loguje i da će u polje moći unijeti naziv ljela nakon čega će moći izvršiti pretragu. Međutim, ni kod jednog od 4 vrste korisnika ne postoji polje u koje se može unijeti naziv jela i izvršiti pretraga.

Koraci za reproduciranje problema:
1. Login kao bilo koji korisnik
2. Ne postoji mogućnost pretrage jela na način opisan u SRSu

Dobijeni rezultat:
-

Očekivani rezultat:
Ispunjen funkcionalni zahtjev

**Comment by admirah** [comment]
Naknadno smo shvatili da nije potrebno omogućiti svim korisnicima tu funkcionalnost, nego je ima samo primaoc narudžbi u tom obliku.
