### ISSUE TITLE
Nemogućnost pregleda broja naručilaca određenog jela (a navedeno u SRSu)

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#19]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
U SRS-u piše da je potrebno da korisnik može vidjeti informaciju o broju naručilaca određenog jela. Međutim, u aplikaciji to nije realizovano.

Koraci za reproduciranje problema:
1. Login kao šef
2. Odaberite tab jelovnik
3. Navedena informacija nije prikazana niti u tabeli niti nakon klika na dugme izmijeni jelo

Dobijeni rezultat:
nema

Očekivani rezultat:
Ispunjen funkcionalni zahtjev

**Comment by admirah** [comment]
Bug je sastavni dio funkcionalnog zahtjeva Pregled informacija o jelima, što je navedeno u issueu https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/issues/20 , nema potrebe cijepati ga u dijelove kako bi se dobilo vise issuea, sve je obuhvaceno sa tim buggom.
