### ISSUE TITLE
Omogućena, a neimplementirana, višestruka izmjena stavki iz tabela

### ISSUE THREAD

**Issue by dzenana1** [SoftverInzenjeringETFSA/SI2015Tim5#21]
Komponenta:
sef.java

commit ID:
65782bcba236371e18665f563d95811ae5b18618

Opis problema:
Nakon odabira više stavki iz tabele (npr. na tabu Sastojci) i klikom na dugme Izmjeni prikazuje se samo interfejs za izmjenu prve selektovane stavke.
![br2](https://cloud.githubusercontent.com/assets/11295655/15301067/2faef27a-1bac-11e6-8288-e1470ec79cc7.png)

 Koraci za reproduciranje problema: 
1.Prijaviti se kao sef.
2.Pristupiti nekom od tabova: Jelovnik,Sastojci,Korisnički računi,Popusti.
3.Selektovati više stavki.
4.Kliknuti na dugme Izmjeni

Dobijeni rezultat
Izmjena samo prve stavke i omogućen višestruki odabir iz tabela

Očekivani rezultat:
Omogućena izmjena ili zabrana višestrukog odabira iz tabela.

**Comment by admirah** [comment]
Popravljeno
