### ISSUE TITLE
Validacija sastojka nije ispravna: naziv i mjerna jedinica mogu biti besmisleni podaci

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#22]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
Kod unosa sastojaka moguće je unijeti potpuno besmislene podatke kao što su:
naziv: 1000000
mjerna jedinica: 10000000

Koraci za reproduciranje problema:
1. Login kao šef
2. Tab sastojci
3. Button Dodaj sastojak
4. Unos nevalidnih podataka

Screenshot:
http://prntscr.com/b4tzpa

Dobijeni rezultat:
Poruka o uspješnom unosu

Očekivani rezultat:
Poruka da uneseni podaci nisu validni

**Comment by mathildaa** [comment]
Maida, molim te dostavi nam spisak svih naziva i mjernih jedinica koje bi se mogle koristiti tako da možemo uraditi i ovu validaciju.
