### ISSUE TITLE
Prikazivanje narudzbi kod korisnika dostavljač nije ispravno

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#24]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
Višestrukim pritiskom na dugme "Prikaži narudžbe" dodaje se jedna te ista narudžba svaki put odnosno možemo dodati jednu narudžbu na spisak bezbroj puta.

Koraci za reproduciranje problema:
1. Login kao dostavljač
2. Pritisnuti button prikaži narudžbe više puta

Screenshot:
http://prntscr.com/b4u3r5

Dobijeni rezultat:
Lista kopija jedne te iste narudžbe

Očekivani rezultat:
Nedodavanje iste narudžbe više puta

**Comment by admirah** [comment]
Popravljeno
