### ISSUE TITLE
Button "Dodaj jelo" kod primaoca narudžbi ne radi ispravno

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#25]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
Pritiskom buttona Dodaj jela nakon odabira jela i količine ne dešava se ništa.

Koraci za reproduciranje problema:
1. Login kao primalac
2. Odabrati jelo 
3. Unijeti količinu
4. Pritisnuti button Dodaj jelo

Dobijeni rezultat:
nema

Očekivani rezultat:
Dodavanje odabranog jela na listu

**Comment by admirah** [comment]
Ispralvjeno
