### ISSUE TITLE
Brisanje korisnika nije navedeno u funkcionalnim zahtjevima ( u SRS-u)

### ISSUE THREAD

**Issue by dzenana1** [SoftverInzenjeringETFSA/SI2015Tim5#26]
Komponenta:
SRS

commitID:
af1627f88296bb17f9944344a03585e0bb84ccef

Opis problema:
Brisanje korisnika nije dokumentovano kao funkcionalni zahtjev u dokumentaciji.

Koraci za reproduciranje problema:
Nije moguće opisati.

Dobijeni rezultat:
//

Očekivani rezultat:
//

**Comment by admirah** [comment]
http://prntscr.com/b56t2f Jeste navedeno.
