### ISSUE TITLE
Dodavanje novog popusta se ne prikazuje u tabeli

### ISSUE THREAD

**Issue by dzenana1** [SoftverInzenjeringETFSA/SI2015Tim5#27]
Komponenta:
sef

commitID:
65782bcba236371e18665f563d95811ae5b18618

Opis problema:
Dodavanje novog popusta se ne prikazuje u tabeli sa popustima, odnosno tabela ne osvježava podatke iz baze.
![popustslika](https://cloud.githubusercontent.com/assets/11295655/15304394/5eefe592-1bbd-11e6-97fa-62a39f9caee8.png)

Koraci za reproduciranje problema:
1.Unijeti podatke za dodavanje novog popusta.
2.Kliknuti na dugme "Završi uređivanje"
3.Fokusirati se na tabelu koja prikazuje popuste.

Dobijeni rezultat:
Popust nije prikazan u tabeli

Očekivani rezultat:
Popust prikazan u tabeli.

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/6913dbc58a54edd21506167f948917e8895bcda6
