### ISSUE TITLE
Izmjena odabranog popusta se ne prikazuje u tabeli

### ISSUE THREAD

**Issue by dzenana1** [SoftverInzenjeringETFSA/SI2015Tim5#28]
Komponenta:
sef

commitID:
65782bcba236371e18665f563d95811ae5b18618

Opis problema:
Izmjena novog popusta se ne prikazuje u tabeli sa popustima, odnosno tabela ne osvježava podatke iz baze.

![popiz](https://cloud.githubusercontent.com/assets/11295655/15304544/39edd442-1bbe-11e6-912a-2fc03757b686.png)

Koraci za reproduciranje problema:
1.Unijeti podatke za izmjenu selektovanogpopusta.
2.Kliknuti na dugme "Završi uređivanje"
3.Fokusirati se na tabelu koja prikazuje popuste.

Dobijeni rezultat:
Popust nije prikazan u tabeli

Očekivani rezultat:
Popust prikazan u tabeli.

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/6913dbc58a54edd21506167f948917e8895bcda6
