### ISSUE TITLE
Validacija Narudžbe nije ispravna

### ISSUE THREAD

**Issue by dzenana1** [SoftverInzenjeringETFSA/SI2015Tim5#29]
Komponenta:
NovaNarudzbaGUI.java

commit ID
85190d444420e3bfa0d753e11fbeb8a06a7b6be3

Opis problema:
Prilikom unosa nepravilnih podataka za količinu jela se pojavljuje nejasna poruka o greški kao i za iste nepravilne podatke dugme Obračunaj nešto računa.
![sl](https://cloud.githubusercontent.com/assets/11295655/15304098/b5a0adf6-1bbb-11e6-8c4e-81014e8eeb6a.png)

Koraci za reproduciranje problema:
1.Prijaviti se kao "primalac".
2.Unijeti neispravne podatke za količinu jela npr"3f"
3.Odabrati dugme "Dodaj jelo" ili "Obračunaj"

Dobijeni rezultat:
Neispravna poruka o greški.

Očekivani rezultat 
Ispravna poruka o greški

**Comment by admirah** [comment]
Ispravljeno

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/6913dbc58a54edd21506167f948917e8895bcda6
