### ISSUE TITLE
Funkcionalni zahtjevi iz SRSa "Evidentiranje pripreme narudžbe" neispravno realizovan

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#30]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
Korisnik kuhar nema mogućnost da evidentira narudžbu čiju pripremu je započeo. (Ne može unijeti vrijeme početka pripreme , niti kao izlaz dobija listu sastojaka potrebnih za pripremu jela)

Koraci za reproduciranje problema:
1. Login kao kuhar
2. Ne postoji mogućnost evidentiranja pripreme narudžbi na način opisan u SRSu

Očekivani rezultat:
Ispunjen funkcionalni zahtjev

**Comment by admirah** [comment]
U SRSU navedeno je da je kao ulaz vrijeme početka pripreme, koji postoji i generiše se pritiskom na dugme. Nije navedeno da mora biti text box niti bilo šta slično. Status se pri preuzmianju mijenja i definiše se VALIDNO vrijeme, kako je naglašeno u SRSu.

**Comment by MaidaB** [comment]
I dalje ostaje lista sastojaka

**Comment by admirah** [comment]
U biti ne ostaje. Bug nije do te forme, problem su podaci u bazi i bug sa dodavanjem sastojaka  ( ako pogledas tabelu SastojciJeloVeza ona je prazna jer dodavanje sastojaka nije dobro implementirano ) , ako se unesu dobri podaci , sto ce biti nakon ispravke tog buga , prikaz sastojaka kuharu sasvim dobro radi. Ako zelis provjeriti mozes rucno samo unijeti podatke u SastojciJeloVeza sa Idovima narudzbe i pripadnih sastojaka i kolicine.

**Comment by MaidaB** [comment]
Kao sto naslov kaze problem je funkcionalni zahtjev (sto obuhvata to sto si navela) a ne forma

**Comment by admirah** [comment]
Da, i ispunjen je. U formi za kuhara se navodi list  narudzbi koja ukljucuje listu sastojaka. ( Funkcionalni zahtjev ispunjen ) Ovdje je problem se ispisuje u tom polju  Navedi za konkretne podatke šta treba da se ispiše kao lista sastojaka. Unesi ih u bazu i onda testiraj dal je ispunjen. Oslanjas se na nase podatke, koji su posljedica drugih bugova. Unesi svoje podatke korektno ( kao što sam ja evo maloprije i dobila tačno ono što funkcionalni zahtjev kaže :  Lista sastojaka potrebnih za pripremu odabrane narudžbe )

http://prnt.sc/b4vacm
