### ISSUE TITLE
Brisanje šefa pretvara šefa u dostavljača

### ISSUE THREAD

**Issue by dzenana1** [SoftverInzenjeringETFSA/SI2015Tim5#31]
Komponenta:
sef

commitID:
65782bcba236371e18665f563d95811ae5b18618

Opis problema:
Nakon brisanja sefa sa forme on u bazi dobije radno mjesto 4 odnosno postaje dostavljač, što nije logički opisano u SRS-u.
![izbrkorisnik](https://cloud.githubusercontent.com/assets/11295655/15304907/3c60482a-1bc0-11e6-81fc-62bd3b4425ce.png)
![uposlbaza](https://cloud.githubusercontent.com/assets/11295655/15304909/410e5d1c-1bc0-11e6-8910-db803f7147c0.png)
![ulogabaza](https://cloud.githubusercontent.com/assets/11295655/15304911/4624beae-1bc0-11e6-8bf7-69e3d53e9f96.png)

Koraci za reproduciranje problema:
1.Prijaviti se kao šef.
2.Pristupiti tabu Korisnički računi.
3.Odabrati šefa iz tabele.
4.Odabrati dugme "Obriši"

Dobijeni rezultat:
Korisnik sa "radnim mjestom" šef postaje "dostavljač"

Očekivani rezultat:
Korisnik se briše iz baze ili dobija funkciju npr. otpuštenog korisnika--nije navedeno u dokumentaciji.

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/6913dbc58a54edd21506167f948917e8895bcda6
