### ISSUE TITLE
Unhandled exception za "Izvještaj o svim narudžbama u vremenskom periodu"

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#32]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
Na svim tabovima button za brisanje izazove izuzetak ukoliko 
nije odabrana nijedna stavka u tabeli.

Koraci za reproduciranje problema:
1. Login kao sef
2. Odabr izvještaja  "Izvještaj o svim narudžbama u vremenskom periodu"
3. Unos VALIDNIH datuma
4. Pritisak na button Generiši izvještaj

Dobijeni rezultat:
Unhandled exception

Screenshot:
http://prntscr.com/b4ujwn

Očekivani rezultat:
Generisan izvještaj

**Comment by mathildaa** [comment]
Popravljeno

**Comment by MaidaB** [comment]
Labela?
