### ISSUE TITLE
Unhandled Exception: Button "Prikaži izvještaj" (izvještaj o vremenu isporuke narudžbe) 

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#33]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
Pritiskom buttonaPrikaži izvještaj ne dešava se ništa.

Koraci za reproduciranje problema:
1. Login kao šef
2. Odabrati izvještaj o vremenu isporeuke narudžbe
3.  Pritisnuti button Prikaži izvještaj

Dobijeni rezultat:
Pritisak na button baca izuzetak

Očekivani rezultat:
Prikaz izvještaja ili poruka da je došlo do greške

**Comment by admirah** [comment]
Možeš li molim te dati screenshot ili više podataka jer ja ne vidim problem s tim - otvara se taj prozor kada se klikne ( to je dodatna funkcionalnost koju nam je asistent tražio poslije  SRSA, pa nije naglašeno u dokumentaciji , dugme generiši izvještaj prikazuje tabelu kao i kod ostalih, a prikaži otvara taj prozor) Moguće da je bug neki, ali ne vidim ga kod sebe, pa ako može više detalja .. http://prntscr.com/b4vjab

**Comment by MaidaB** [comment]
Nemam sta prikazati na screenshotu. Jednostavno odaberem statistički izvještaj o vremenu isporuke narudžbe, kliknem dugme Odaberi izvještaj pa kliknem dugme Prikaži izvještaj. Ne desi se ništa

**Comment by admirah** [comment]
Opet, problem je do podataka u bazi. Dugme radi, ta funkcionalnost je ispunjena . Unosite svoje podatke pa onda testirajte. Ja nemam sta popravljati ovdje
