### ISSUE TITLE
Nepotpuna povratna poruka kod unosa podataka koji nisu validni na login-u

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#34]
Komponenta:
LoginGUI

commit ID:
ffa5dcc6f67f7c79bbd41dccb5ca0662534fc3ee

Opis problema:
Prilikom unosa nevalidnih podataka pri pokušaju prijave na sistem, dobije se poruka "Pogrešan un"

Koraci za reproduciranje problema:
1. Login sa neispravnim podacima (primjer prazno korisničko ime i lozinka)
2. Pritisak na dugme "Prijava"

Dobijeni rezultat:
Nejasna/nepotpuna povratna poruka

Screenshot:
http://pokit.org/get/?f53b1552de8d4cbd029964f46a2b12f7.jpg

Očekivani rezultat:
Ispravna poruka

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/6913dbc58a54edd21506167f948917e8895bcda6
