### ISSUE TITLE
Login sa validnim podacima korisnika koji ne postoji ne vraca odgovarajuću poruku

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#35]
Komponenta:
LoginGUI

commit ID:
ffa5dcc

Opis problema:
Prilikom unosa validnih podataka za login za korisnika koji ne postoji u sistemu, dobije se povratna poruka "Pogrešan un". Ovo je problematično jer neki korisnik onda ne zna da li je stvarno pogrešan unos ili njegov nalog nije kreiran

Koraci za reproduciranje problema:
1. Pokretanje aplikacije
2. Unos validnih podataka za nepostojećeg korisnika ( primjer: Korisničko ime: Amar, Lozinka:amaramaramar)
3. Pritisak na dugme "Prijava"

Dobijeni rezultat:
Nejasna/nepotpuna povratna poruka

Screenshot:
http://pokit.org/get/?20d13c8dfe7e34c177cab843244a7945.jpg

Očekivani rezultat:
Ispravna poruka

**Comment by admirah** [comment]
Da ali nigdje u SRSU nije definisano to kao zahtjev. To su lične prefernecije šta bi bilo ljepše i bolje, a ne ono što je srsom zadano.

**Comment by AmarPanjeta** [comment]
Ne radi se o ličnim preferencama ako korisnik ne zna da li njegov account uopšte postoji u sistemu.

**Comment by mathildaa** [comment]
Ukoliko se unese korektar username a pogrešan password (što je situacija kada korisnik POSTOJI u sistemu), ispiše se obavještenje o pogrešnom PW-u, a ukoliko se unese pogrešan username onda se ispiše obavještenje o tome. Zašto nekome ne bi bilo jasno da "pogrešan username" znači da taj username ne postoji u sistemu?! 

Neki korisnik možda IMA nalog u sistemu, ali je pogriješio jedno slovo prilikom kucanja username-a, prema tebi njemu bi onda trebalo ispisati poruku "POSTOJITE U SISTEMU ALI NISTE DOBRO UKUCALI UN" (?!)

**Comment by AmarPanjeta** [comment]
Ovdje je ocigledno doslo do nesporazuma. U ovom bugu je oznaceno kao razultat oznaceno nejasna povratna poruka. Meni licno ne znaci nista Pogresan un, iako je un skracenica od username, pogotovo zato sto na formi za login pise korisnicka sifra. Ovo je i dalje legitiman bug, a rjesava se jednostavno izmjenom povratne poruke u nesto jasnije (npr. Pogresno korisnicko ime). Zato treba biti oznaceno kao bug.

**Comment by admirah** [comment]
Onda je bug duplikat, vec si to naveo i to ce biti rijeseno:)

**Comment by AmarPanjeta** [comment]
Super :D
