### ISSUE TITLE
Validacija datuma (navedena u SRSu) nije urađena

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#36]
Komponenta:
Telefonske narudžbe

commit ID:
65782bcba236371e18665f563d95811ae5b18618

Opis problema:
Kod izvjještaja o narudžbama u vremenskom periodu validacija da prvi datum bude manji od drugog nije urađena.

Koraci za reproduciranje problema:
1. Login kao šef
2. Odabrati izvještaj  o narudžbama u vremenskom periodu 
3. Unijeti prvi datum veći od drugog
4. Pritisnuti button Generiši izvještaj

Dobijeni rezultat:
Prikaz strukture izvještaja (bez podataka)

Očekivani rezultat:
Poruka da uneseni datumi nisu validni

**Comment by mathildaa** [comment]
riješeno via 2168e3f

**Comment by MaidaB** [comment]
Labela?
