### ISSUE TITLE
Dodavanje popusta radi, ali se izmjena vidi tek nakon ponovnog prijavljivanja

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#40]
Komponenta:
Interfejs za sefa (sef.java)

commit ID:
ffa5dcc

Opis problema:
Nakon dodavanja popusta kroz interfejs šefa, popust biva dodan u sistem. Ipak, odgovarajuće dodavanje nije vidljivo odmah već je potrebno odjaviti se i prijaviti se ponovo

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na tab "Popusti"
3. Unos podataka o popustu
4. Pritisak na dugme "Završi uređivanje"

Dobijeni rezultat:
Dodani popust nije odmah vidljiv u tabeli

Screenshot koraka akcije:
http://pokit.org/get/?d35521d193e61eb477c627bc775f7bce.jpg

Screenshot nakon izvršene akcije:
http://pokit.org/get/?0ed5ceda8c5fc5daba45a49c26d5c8c5.jpg

Očekivani rezultat:
Dodani popust se odmah prikazuje u tabeli

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/issues/27
