### ISSUE TITLE
Validacija imena dostavljača (navedena u SRSu) nije urađena

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#41]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
U SRSu navedeno kao uslov za validaciju za izvješta za dostavljača da ime sadrži više od 3 slova a moguće je kreirati dostavljača sa imenom koje to ne zadovoljava.

Koraci za reproduciranje problema:
1. Login kao šef
2. Tab Korisnici
3. Kreiranje dostavljača sa imenom Ali

Dobijeni rezultat:
Poruka da je dostavljač kreiran

Očekivani rezultat:
Poruka da je došlo do greške

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/6913dbc58a54edd21506167f948917e8895bcda6
