### ISSUE TITLE
Validacija kod dodavanja jela za narudžbu daje nejasne poruke

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#42]
Komponenta:
Interfejs za dodavanje narudzbe

commit ID:
ffa5dcc

Opis problema:
Nakon odabira jela iz liste i priska na dugme dodaj jelo, prikaže se nejasna poruka koja se tiče validacije: 'For input string:"" '

Koraci za reproduciranje problema:
1. Login sa nalogom koji ima opciju pravljenja narudžbi
2. Pritisak na dugme "Nova narudžba"
3. Odabir jela iz liste
4. Pritisak na dugme "Dodaj jelo"

Dobijeni rezultat:
Poruka:  'For input string:"" '

Screenshot:
http://pokit.org/get/?c0b503c7f4c235d5e8e9f0e451cb2897.jpg

Očekivani rezultat:
Ispravna povratna poruka

**Comment by admirah** [comment]
Ispralvjeno
