### ISSUE TITLE
Ako se ne odabere jelo prilikom dodavanja narudzbe, sistem vraca prazan messagebox

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#43]
Komponenta:
Interfejs za dodavanje narudzbe

commit ID:
ffa5dcc

Opis problema:
Nakon unosa količine na formi za dodavanje naruzdbe, a da prije toga nije odabran jelo i pritiska na dugme "Dodaj jelo", prikazuje se prazan messagebox.

Koraci za reproduciranje problema:
1. Login sa nalogom koji ima opciju pravljenja narudžbi
2. Pritisak na dugme "Nova narudžba"
3. Unos validne količine jela
4. Pritisak na dugme "Dodaj jelo"

Dobijeni rezultat:
Prazan messagebox

Screenshot:
http://pokit.org/get/?49071fb626d4feec35d4d908dab6e990.jpg

Očekivani rezultat:
Bilo kakva povratna poruka

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/issues/29
