### ISSUE TITLE
Prilikom dodavanja novog jela, kucanje duzeg teksta uzrokuje da se on dodaje van granica prikaza

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#44]
Komponenta:
Interfejs za dodavanje novog jela

commit ID:
ffa5dcc

Opis problema:
Prilikom kucanja dužeg opisa u polje "Opis" na interfejsu dodavanje jela, tekst će nakon određene dužine izaći van granica prikaza polja. Tekst koji je van prikaza se sačuva nakon kreiranja jela.

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na tab "Jelovnik"
3. Unos podataka o jelu
4. Unos dužeg opisa bez korištenja tipke "Enter" (npr. tekst "ako kucam duzi tekst, on ce izaci izvan granica i nece biti vidljiv" )

Dobijeni rezultat:
Unijeti tekst se ne prikazuje

Screenshot:
http://pokit.org/get/?b7615acadb1311d2e3efbed5cbee34c2.jpg

Očekivani rezultat:
Tekst unutar polja za prikaz

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/b687bbe7c7634b1af3b338ca20cf8d38378649df
