### ISSUE TITLE
Nemaskirana šifra prilikom logina

### ISSUE THREAD

**Issue by dzenana1** [SoftverInzenjeringETFSA/SI2015Tim5#45]
Komponenta:
login

commitID:
85190d444420e3bfa0d753e11fbeb8a06a7b6be3

Opis problema:
Prilikom unosa šifre kod prijave na sistem, šifra nije maskirana nego je njen sadržaj vidljiv kako korisniku koji se prijavljuje tako i bilo kojem drugom korisniku koji ima pregled na aplikaciju.

![screenshot_2](https://cloud.githubusercontent.com/assets/11295655/15306546/c2682a86-1bcb-11e6-914a-aa4484fa0524.png)

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju.
2.Unijeti korisničko ime i šifru korisnika.
3.Fokusirati se na polje za unos šifre korisnika.

Dobijeni rezultat:
Nemaskirana šifra

Očekivani rezultat:
Maskirana šifra

**Comment by admirah** [comment]
ispravljeno
