### ISSUE TITLE
Ime ulogovanog korisnika nije upotpunosti prikazano na formi 

### ISSUE THREAD

**Issue by dzenana1** [SoftverInzenjeringETFSA/SI2015Tim5#46]
Komponenta:
KuharGUI

commitID
85190d444420e3bfa0d753e11fbeb8a06a7b6be3

Opis problema:
Ime ulogovanog korisnika nije upotpunosti prikazano na formi.
![screenshot_1](https://cloud.githubusercontent.com/assets/11295655/15306646/badad894-1bcc-11e6-9574-824f355d8810.png)

što je bilo predviđeno unutar UserInterface specifikacije
![screenshot_3](https://cloud.githubusercontent.com/assets/11295655/15306657/dddb0684-1bcc-11e6-8c7d-93b16c1948eb.png)

Koraci za reproduciranje problema:
1.Prijaviti se na sistem sa ulogom mkuhar.
Fokusirati se na labelu koja označava poruku dobrodošlice

**Comment by admirah** [comment]
Ispravljeno
