### ISSUE TITLE
Šef ima mogućnost da obriše sebe iz sistema dok je prijavljen na sistem, a nakon toga može i dalje koristiti sistem

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#47]
Komponenta:
Interfejs za sefa (sef.java)

commit ID:
ffa5dcc

Opis problema:
Šef može sebe da izabere iz liste korisnika i obriše svoj nalog, iako je prijavljen na sistem sa istim. Nakon toga, može da radi sve akcije koje je inače mogao kao šef, dok se ne odjavi sa sistema.

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na tab "Korisnički računi"
3. Odabir računa sa kojim smo se prijavili
4. Pritisak na opciju obriši

Dobijeni rezultat:
Poruka o uspješnosti brisanja računa, i obrisan račun iz sistema

Očekivani rezultat:
Poruka o tome da brisanje nije moguće ili brisanje naloga uz odjavu

**Comment by AmarPanjeta** [comment]
Kojeg je ovo issuea duplikat?

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/issues/38
