### ISSUE TITLE
Pritisak na opcije dodaj ili izmijeni ne daju povratne informacije u slucaju da nije odabrana neka od stavki u tabeli

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#48]
Komponenta:
Interfejs za šefa

commit ID:
ffa5dcc

Opis problema:
Ako se ne odabere ništa u tabeli, a pritisne se na dugme za brisanje ili izmjenu, ne desi se ništa. To se dešava na tabovima za "Jelovnik", "Sastojci","Korisnički računi" i "Popusti"

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na jedan od tabova: Jelovnik, Sastojci, Korisnički računi ili Popusti
3. Pritisak na dugme za izmjenu ili brisanje (napomena: ne odabrati ništa u odgovarajućoj tabeli)

Dobijeni rezultat:
Ništa se ne dogodi

Očekivani rezultat:
Poruka o tome da ništa nije odabrano u tabeli

**Comment by mathildaa** [comment]
Kada ništa nije obrisano i ne treba se ništa desiti. Stvar je lične preferencije da li treba ispisati poruku o tome da nije ništa izabrano ili samo ignorisati zahtjev.

**Comment by AmarPanjeta** [comment]
Nije stvar licne preferencije. Korisnik mora znati sta treba da uradi da bi se nesto obrisalo/izmijenilo. Ovako ne zna da li se ocekuje da mora odabrati nesto iz tabele ili ce se otvoriti posebna forma u kojoj se unosi ime objekta koji se brise ili dugme uopste ne radi.

**Comment by AmarPanjeta** [comment]
Nije stvar licne preferencije. Korisnik mora znati sta treba da uradi da bi se nesto obrisalo/izmijenilo. Ovako ne zna da li se ocekuje da mora odabrati nesto iz tabele ili ce se otvoriti posebna forma u kojoj se unosi ime objekta koji se brise ili dugme uopste ne radi.

**Comment by admirah** [comment]
Nije navedeno da ce se desiti to u SRSu, kupac se nije zalio na to. Tako da nije bug
