### ISSUE TITLE
Dodavanje korisnika ne radi ispravno - ne dodjeljuje se ispravno radno mjesto

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#49]
Komponenta:
Interfejs za dodavanje korisnika

commit ID:
ffa5dcc

Opis problema:
Prilikom dodavanja korisnika se odabere radno mjesto za koje je zadužen, ali kada se sačuva, dodijeli mu se drugo radno mjesto. Ovo važi za bilo koju opciju odabranu za radno mjesto.

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na tab "Korisnički računi"
3. Pritisak na dugme "Dodaj novog radnika"
4. Unos validnih podataka o radniku
5. Odabir nekog radnog mjesta
6. Pritisak na dugme "Završi uređivanje"

Dobijeni rezultat:
Novi korisnik sa pogrešnim radnim mjestom

Screenshot unosa:
http://pokit.org/get/?94b73e31e40ad76b49de17c05c0b5a61.jpg

Screenshot nakon dodavanja korisnika:
http://pokit.org/get/?48ed97b591d8ea215b5d15c1b976cf51.jpg

Očekivani rezultat:
Novi korisnik sa ispravnim radnim mjestom

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/b687bbe7c7634b1af3b338ca20cf8d38378649df
