### ISSUE TITLE
Prilikom unosa nevalidnog datuma kod dodavanja korisnika, on se pretvori u drugi datum, koji nije smislen

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#50]
Komponenta:
Interfejs za dodavanje korisnika

commit ID:
ffa5dcc

Opis problema:
Kada se unese nevalidan datum na formi za dodavanje korisnika, on se pretvori u drugi datum nakon što se pritisne na nešto vam textboxa (kontrola izgubi focus). Taj datum nije očekivan za dati unos.

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na tab "Korisnički računi"
3. Pritisak na dugme "Dodaj novog radnika"
4. Unos nevalidnog datuma (primjer: 99/99/9999)
5. Pritisak na bilo šta izvan textboxa

Dobijeni rezultat:
Novi, neočekivan datum (za primjer iznad: 07/06/10007)

Screenshot unosa:
http://pokit.org/get/?0daaf3b70dd81fd53d20886432a7059f.jpg

Screenshot nakon što kontrola izgubi fokus:
http://pokit.org/get/?72cfb944d28c5da74473adef8c74f479.jpg

Očekivani rezultat:
Poruka o unosu koji nije validan

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/issues/16
