### ISSUE TITLE
Datum u formatu dd.mm.yyyy se izbrise na formi za unos korisnika, nakon što kontrola izgubi fokus

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#51]
Komponenta:
Interfejs za dodavanje korisnika

commit ID:
ffa5dcc

Opis problema:
Prilikom dodavanja korisnika se unese neki datum u formatu dd.mm.yyyy. Nakon što kontrola izgubi fokus, unijeti datum nestane i korisnik ne dobije nikakvu povratnu poruku o tome.

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na tab "Korisnički računi"
3. Pritisak na dugme "Dodaj novog radnika"
4. Unos datuma u formatu dd.mm.yyyy ( primjer 12.2.2012 )
5. Klik mišem na bilo šta izvan kontrole za unos datuma

Dobijeni rezultat:
Polje za unos datuma je prazno

Screenshot unosa:
http://pokit.org/get/?cd8381ddba701401e74fc4a1dd0b1c54.jpg

Screenshot nakon što kontrola izgubi fokus:
http://pokit.org/get/?5462d30c23c44b7a68fa94c58553cb0e.jpg

Očekivani rezultat:
Povratna poruka o formatu datuma koji je potrebno unijeti

**Comment by emhuskic** [comment]
U SRS-u je definisan format datuma kao: dd/MM/yyyy, pa je jedino takav datum moguce unijeti. Drago nam je da validacija prolazi :)

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/issues/16 Vec se pricalo o validaciji datuma
