### ISSUE TITLE
Kada se otvori forma za izmjenu podataka o korisniku, datum se ucita u pogresnom formatu

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#53]
Komponenta:
Forma za izmjenu podataka o korisničkom računu

commit ID:
ffa5dcc

Opis problema:
Kada se odabere neki korisnik iz tabele korisnika i pritisne se na opciju "Izmjeni podatke", datum koji se učita u odgovarajuće polje je u pogrešnom formatu. To uzrokuje da korisnik ne može napraviti izmjene, dok ne napravi izmjene kako bi datum bio u odgovarajućem formatu (iako bi se trebao datum ispravno učitati)

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na tab "Korisnički računi"
3. Odabir korisnika iz tabele
4. Pritisak na dugme "Izmjeni podatke"

Dobijeni rezultat:
Polje datum se učita u pogrešnom formatu

Screenshot:
http://pokit.org/get/?1fd98ca7a2c9d19d53a1aeda75a562f9.jpg

Očekivani rezultat:
Polje datum se učita u ispravnom formatu

**Comment by emhuskic** [comment]
Polje datum se ucita u formatu kakav je u bazi. Ako je u bazi ispravan datum, i na formi ce biti.. Uzrok ove "greske" je rucno pisana baza, sto u realnom okruzenju nece biti slucaj  (svi korisnici se trebaju unijeti putem forme).

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/issues/16 kako se otvara ista forma, jedan problem == drugi problem
