### ISSUE TITLE
Opcija izmjeni lozinku otvara formu za izmjenu podataka, moguća izmjena podataka koji nisu lozinka

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#54]
Komponenta:
Interfejs za šefa/ interfejs za izmjenu korisnika

commit ID:
ffa5dcc

Opis problema:
Kada se pritisne na dugme "Izmjena lozinke" na tabu "Korisnički računi" , otvori se forma koja se prikazuje i kada se pritisne na dugme "Izmjeni podatke". Ova forma se također može koristiti za izmjenu podataka pored lozinke, što očigledno ne bi trebalo biti moguće za opciju "Izmjena lozinke"

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na tab "Korisnički računi"
3. Odabir korisnika
4. Pritisak na dugme "Izmjena lozinke"
5. Izmjena podataka koji nisu lozinka
6. Pritisak na dugme "Završi uređivanje"

Dobijeni rezultat:
Izmjena podataka koji nisu lozinka

Očekivani rezultat:
Nemogućnost izmjene podataka koji nisu lozinka

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/b687bbe7c7634b1af3b338ca20cf8d38378649df
