### ISSUE TITLE
Problem sa odjavljivanjem - moguće korisititi funkcionalnosti neke forme koja je ostala otvorena nakon odjavljivanja sa sistema

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#55]
Komponenta:
Sistem

commit ID:
ffa5dcc

Opis problema:
Sistem posjeduje nekoliko formi koje se otvaraju za različite funkcionalnosti. Ako neka od njih ostane otvorena nakon odjavljivanja sa sistema, moguće je koristiti njenu punu funkcionalnost, a to ne bi trebalo biti jer više nismo prijavljeni na sistem.

Koraci za reproduciranje problema (prikazat ćemo to na jednom primjeri, iako ih ima više):
1. Pokretanje aplikacije
2. Prijavljivanje sa korisničkim računom šefa
3. Pritisak na tab "Sastojci"
4. Pritisak na dugme "Dodaj sastojak"
5. Pritisak na glavnu formu (bez zatvaranja forme koja se otvori u prethodnom koraku)
6. Odabir opcije za odjavljianje sa sistema
7. Unos podataka o sastojku
8. Pritisak na dugme "Završi uređivanje"

Dobijeni rezultat:
Dodavanje novog sastojka

Screenshot:
http://pokit.org/get/?188a66d04cdc218c516ccc078c9a23c4.jpg

Očekivani rezultat:
Poruka da se moramo ponovo prijaviti na sistem

**Comment by admirah** [comment]
Popravljeno
