### ISSUE TITLE
Grupa gresaka: Na formama za dodavanje jela, korisnika, sastojaka i popusta u sistem, podaci se ne azuriraju odmah u odgovarajucoj tabeli

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#56]
Komponenta:
Interfejs za šefa zajedno sa interfejsima za dodavanje objekata
commit ID:
ffa5dcc

Opis problema:
Prilikom dodavanja novih jela, korisnika, sastojaka ili popusta u sistem, odgovarajuca tabela na glavnoj formi se ne azurira. 

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na tab "Sastojci"
3. Pritisan na dugme "Dodaj sastojak" 
4. Unos validnih podataka
5. Pritisak na dugme "Zavrsi uredivanje"

Dobijeni rezultat:
Podaci se sacuvaju u sistem, ali se ne prikazu u odgovarajucoj tabeli na glavnoj formi

Očekivani rezultat:
Azuriranje odgovarajuce tabele na glavnoj formi

**Comment by AmarPanjeta** [comment]
Kojeg je ovo issuea duplikat?

**Comment by AmarPanjeta** [comment]
Nije duplikat.

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/issues/28 
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/issues/27
