### ISSUE TITLE
Prilikom kucanja u combobox Raspon cijena na formi za dodavanje popusta te potvrdjivanja izmjene, kreira se neispravan popust

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#57]
Komponenta:
Interfejs za izmjenu popusta

commit ID:
ffa5dcc

Opis problema:
Nakon što se otvori forma za izmjenu popusta, imamo mogućnost da kucamo proizvolji tekst u combobox "Raspon cijena". Čak i ako unesemo validne podatke i pritisnemo na dugme "Završi uređivanje", kreirat će se novi popust sa rasponom cijena od 0.00 do 0.00

Koraci za reproduciranje problema:
1. Login kao šef
2. Pritisak na tab "Popusti"
3. Odabir popusta iz tabele
4. Pritisak na dugme "Izmijeni popust"
5. Kucanje ispravnih podataka u combobox (primjer "20-22KM")
6. Pritisak na dugme "Završi uređivanje"

Dobijeni rezultat:
Novi popust sa rasponom cijena od 0.00 do 0.00

Screenshot 1:
http://pokit.org/get/?8696c76371245946a6ca5659a39919a1.jpg

Screenshot 2:
http://pokit.org/get/?10c175e002887eab30df124cd03c3f6e.jpg

Očekivani rezultat:
Izmijenjen popust koji smo odabrali za izmjenjivanje

**Comment by admirah** [comment]
Popravljeno.
