### ISSUE TITLE
Kada se prilikom izmjene sastojka unese ime koje postoji i pirisne se dugme za potvrdivanje, dobije se poruka da je sastojak uspjesno dodan/izmjenjen

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#59]
Komponenta:
Interfejs za izmjenjivanje sastojaka

commit ID:
ffa5dcc

Opis problema:
Na formi za izmjenjivanje se proizvoda se unese ime nekog drugog proizvoda koji vec postoji. Nakon sto se pritisne dugme "Zavrsi uredivanje", dobije se poruka da je sastojak uspjesno dodan/izmijenjen. Nikakve promjene se ipak ne sačuvaju u bazi.

Koraci za reproduciranje problema (prikazat ćemo to na jednom primjeri, iako ih ima više):
1. Prijavljivanje sa korisničkim računom šefa
2. Pritisak na tab "Sastojci"
3. Pritisak na dugme "Izmijeni sastojak"
5. Unos imena koje već postoji (primjer: biber)
6. Unos ostalih validnih podataka
7. Pritisak na dugme "Završi uređivanje"

Dobijeni rezultat:
Poruka: Uspjesno dodan/izmijenjen sastojak

Screenshot:
http://pokit.org/get/?442e1d170549bd06487cd6b70731121a.jpg

Očekivani rezultat:
Poruka da nije mogue dodati sastojak sa imenom koje vec postoji

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/b687bbe7c7634b1af3b338ca20cf8d38378649df
