### ISSUE TITLE
Nakon povlačenja commita 793655063c8eb003ea180aae8b6a7ab6f709da6b, ne radi login sa korisnikom dzanafer

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#60]
Komponenta:
Interfejs login

commit ID:
793655063c8eb003ea180aae8b6a7ab6f709da6b

Opis problema:
Nakon povlačenja pomenutog commita, unos radi za sve defaultne korisnike sem korisnika sa korisničkim imenom dzanafer i lozinkom pw. Dobije se poruka "Could not extract ResultSet"

Koraci za reproduciranje problema (prikazat ćemo to na jednom primjeri, iako ih ima više):
1. Otvaranje interfejsa za Login
2. Unos podataka Korisničko ime: dzanafer, lozinka: pw

Dobijeni rezultat:
Poruka "Could not extract ResultSet"

Screenshot:
http://pokit.org/get/?e9b0e135776d9c28f8403f275281656b.jpg

Očekivani rezultat:
Uspješno prijavljivanje na sistem

**Comment by admirah** [comment]
Naravno da ne može. Sa novim commitom dolazi i nova baza. Importuje se baza, pa onda pokusa registrovati
