### ISSUE TITLE
Zadnju verziju skripte za inicijalizaciju baze, koja je povučena sa commitom 793655063c8eb003ea180aae8b6a7ab6f709da6b, nije moguće pokrenuti

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#61]
Komponenta:
init.sql

commit ID:
793655063c8eb003ea180aae8b6a7ab6f709da6b

Opis problema:
Nakon povlačenja pomenutog commita i pokušaja pokretanja skripte, skripta se ne izvrši uz povratnu poruku:
http://pokit.org/get/?57bdcab265f608f874eeac6cee4a03b2.jpg

Koraci za reproduciranje problema (prikazat ćemo to na jednom primjeri, iako ih ima više):
1. Otvaranje MySQL workbencha
2. Pronalazak i otvaranje skripte init.sql
3. Pokretanje skripte

Dobijeni rezultat:
Skripta se ne izvrši

Screenshot:
http://pokit.org/get/?2ba69c0f7569d140998022a8c2ea9c51.jpg

Očekivani rezultat:
Skripta se izvrši

**Comment by admirah** [comment]
Pri importu baze odabere se u koju zelis importovati,ili setuj defaultnu. Niko drugi nema problem s tim.

**Comment by AmarPanjeta** [comment]
U skripti se može nemjesti da sama skripta odabire bazu/scheme-u, tako što se ispred imena tabele doda ime baze praćeno tačkom ( primjer za tabelu jelo u vašem slučaju `si2015tim5`.`jelo` ). Tako se pravi ispravna skripta za inicijalizaciju, nije cilj da korisnik sam mora da isprobava dok mu ne prođe.
