### ISSUE TITLE
Skripta za inicijalizaciju baze nije ispravna i ne koristi se u skladu sa uputstvima za postavljanje radnog okruzenja

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#62]
Komponenta:
init.sql

commit ID:
793655063c8eb003ea180aae8b6a7ab6f709da6b

Opis problema:
U uputstvima piše da se pokrene skripta za inicijalizaciju baze i ona "uradi sav posao". Skripta ne kreira scheme-u pod nazivom "si2015tim5", a korisnik ni na koji način nije informisan da ta scheme-a treba da postoji, tako da nije moguće ispravno podesiti bazu.

Koraci za reproduciranje problema (prikazat ćemo to na jednom primjeri, iako ih ima više):
1. Otvaranje MySQL workbenc-a
2. Pronalazak i otvaranje init.sql skripte
3. Pokretanje skripte

Dobijeni rezultat:
Ne kreira se baza

Očekivani rezultat:
Skripta koja kreira scheme-u i odgovarajuću hijerarhiju tabela

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/b687bbe7c7634b1af3b338ca20cf8d38378649df
