### ISSUE TITLE
Prilikom dodavanja popusta koji već postoji, pojavljuje se poruka "Indeks je: n", proizvoljan broj

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#63]
Komponenta:
Interfejs za dodavanje popusta

commit ID:
7936550

Opis problema:
Prilikom dodavanja popusta koji već postoji, prikazuje se poruka "Indeks je: n", gdje je n proizvoljan broj.

Koraci za reproduciranje problema (prikazat ćemo to na jednom primjeri, iako ih ima više):
1. Login kao šef
2. Pritisak na tab "Popusti"
3. Pritisak na dugme "Dodaj popust"
4. U comboboxu "Raspon cijena", biramo neki popust koji je već dodan
5. Pritisak na dugme "Završi uređivanje"

Dobijeni rezultat:
Poruka: "Indeks je: 5"

Screenshot:
http://pokit.org/get/?a6f13487341e19f994ddeecaedc1f9c1.jpg

Očekivani rezultat:
Poruka: Uspješno ste dodali/izmjenili popust.

**Comment by admirah** [comment]
Nije oznaceno nigdje da su bugovi vezani za popuste ispravljeni naglaseno je vec vise puta

**Comment by AmarPanjeta** [comment]
Ovo je novi bug i zato se ne moze oznaciti kao duplikat.
