### ISSUE TITLE
Mogućnost dodavanja korisnika sa neispravnim podacima za ime i prezime

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#64]
Komponenta:
Interfejs za dodavanje korisnika

commit ID:
424ab0b444f1ec21225c76e8ecdea978ed26d243

Opis problema:
Na formi za dodavanje korisnika ima polje "Ime i Prezime". U to polje se očekuje unos minimalno dva stingovna podatka. Tu je moguće unijeti samo jedan string.Ili čak jedan broj i takav korisnik će biti sačuvan u sistem

Koraci za reproduciranje problema (prikazat ćemo to na jednom primjeri, iako ih ima više):
1. Prijavljivanje sa korisničkim računom šefa
2. Pritisak na tab "Korisnički računi"
3. Pritisak na dugme "Dodaj novog radnika"
4. Unos za polje "Ime i prezime" : 1
5. Unos ostalih. validnih podataka
6. Pritisak na dugme "Završi uređivanje"

Dobijeni rezultat:
Poruka: Radnik uspješno dodan/izmijenjen.

Screenshot:
http://pokit.org/get/?cfbbca082ac31071650a9d4de683caed.jpg

Očekivani rezultat:
Poruka da polje ime i prezime nije validno

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/issues/41
