### ISSUE TITLE
Password ne mora zadovoljavati formu navedenu u SRSu

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#66]
Komponenta:
Interfejs za dodavanje korisnika / izmjenu korisnika / izmjenu lozinke korisnika

commit ID:
424ab0b

Opis problema:
Prilikom dodavanja ili izmjene lozinke, moguce je unijeti lozinku koja ne zadovoljava formu napisanu u SRS-u:
http://pokit.org/get/?c6de1227cfabc6b15d90ff45e1d0db5e.jpg

Koraci za reproduciranje problema:
1. Prijavljivanje sa korisničkim računom kuhara
2. Pritisak na tab "Korisnički računi"
3. Pritisak na dugme "Dodaj novog radnika"
4. Unos validnih podataka
5. Unos lozinke i potvrde lozinke: 1

Dobijeni rezultat:
Poruka: Radnik je uspješno dodan/izmjenjen

Očekivani rezultat:
Poruka da lozinka ne zadovoljava traženi format.

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/b687bbe7c7634b1af3b338ca20cf8d38378649df
