### ISSUE TITLE
GUI izmjena radnika . labele se ne prikazuju cijele

### ISSUE THREAD

**Issue by ammar2403** [SoftverInzenjeringETFSA/SI2015Tim5#67]
Komponenta:
Interfejs  Izmjena radnika 

commit ID:
16be9bd

Opis problema:
Prilikom otvaranja interfejsa labele se ne prikazuju cijele vec polovićno
http://pokit.org/get/?8157e8671e51af9cead1c5356b4f6d99.jpg

Koraci za reproduciranje problema:
1. Otvaranje forme UnosIzmjenaRadnika.java

Dobijeni rezultat:
Ime i prezi.... ,  Lozi..... , Datum rođe.... itd

Očekivani rezultat:
Ime i prezime , Lozinka , Datum rođenja itd

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/b687bbe7c7634b1af3b338ca20cf8d38378649df
