### ISSUE TITLE
Nefunkcionalni zahtjev 2 iz SRS-a nije ispunjen

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#69]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
U SRSu navedeno slijedeće:
NFZ 2. Grafički korisnički interfejs će podrazumijevati pored standardnih, jednostavnih
kontrola, i kontrole sa grafičkim prikazom jela iz ponude.

Dobijeni rezultat:
Ne postoji grafički prikaz niti jednog jela.

Očekivani rezultat:
Ispunjen zahtjev.

**Comment by admirah** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim5/commit/b687bbe7c7634b1af3b338ca20cf8d38378649df
