### ISSUE TITLE
Izdavanje računa navedeno u SRSu nije urađeno

### ISSUE THREAD

**Issue by MaidaB** [SoftverInzenjeringETFSA/SI2015Tim5#70]
Komponenta:
Telefonske narudžbe

commit ID:
65782bc

Opis problema:
U SRSu navedeno slijedeće:
Na osnovu stava 6. ovog člana, naš sistem će omogućiti izdavanje računa za pružene
ugostiteljske usluge.

Dobijeni rezultat:
Ne postoji bilo kakva vrsta računa.

Očekivani rezultat:
Izdavanje računa

**Comment by mathildaa** [comment]
Kao rezultat klika na dugme PREUZMI na formi za dostavljača generiše se PDF file - račun. To je bilo implementirano u commitu sa redovnog roka. Ostali učesnici nemaju potrebu za izdavanjem računa.
