### ISSUE TITLE
Login izbacuje poruku "Pogrešan pw"

### ISSUE THREAD

**Issue by amirsabanovic** [SoftverInzenjeringETFSA/SI2015Tim5#71]
Komponenta: LoginGUI.java

Commit ID: f9e089d

1. Pokrenuti formu LoginGUI.java
2. Ukucati 'emina' i 'emina' u 'Korisničko ime' i 'Lozinka', respektivno.

Očekivani rezultat:
Uspješna prijava

Dobijeni rezultat:
Sistem izbacuje poruku 'Pogrešan pw'

**Comment by admirah** [comment]
Nisu dobri podaci u bazi
