### ISSUE TITLE
Polje opis se validira kao obavezno, iako u SRS-u nije oznaceno kao obavezno polje

### ISSUE THREAD

**Issue by AmarPanjeta** [SoftverInzenjeringETFSA/SI2015Tim5#72]
Komponenta:
Dodavanje i izmjena sastojaka

commit ID:
65782bc

Opis problema:
Prilikom dodavanja ili izmjene sastojka, nije moguce opis ostaviti praznim. Medutim, opis u SRS-u nije oznacen kao obavezan, tako da bi trebalo biti moguce.

Dio iz SRS-a:
http://pokit.org/get/?6536c5de79a2597492bfbba7dbe612d6.jpg

Koraci za reproduciranje problema:
1. Prijavljivanje sa korisničkim računom sefa
2. Pritisak na tab "Sastojci"
3. Odabir više sastojka iz liste
4. Pritisak na dugme "Izmjeni sastojak"
5. Brisanje sadrzaja polja opis, tako da ono ostane prazno
6. Pritisak na dugme "Zavrsi uređivanje"

Dobijeni rezultat:
Povratna poruka: Popunite polje opis

Screenshot:
http://pokit.org/get/?8d5715a8cb332bc3f8f1772b9e2608bc.jpg

Ocekivani rezultat:
Uspjesan unos/izmjena

**Comment by mathildaa** [comment]
riješeno via 2168e3f82f70d607619fcb747d75b9f0260c843f
