### ISSUE TITLE
Nova funkcionalnost

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2015Tim5#9]
Dodati za svako jelo i sastojke sa količinama.
Npr.
Pileći fileti: 2 fileta, 30 ml kečapa, 1 list salate, 1 somun
Ćevapi, velika porcija: 1 somun, 10 ćevapa, 30 gr luka
...
Narudžba: 2 pieća fileta, 1 ćevapi, velika porcija.
....
Kuhar dobije narudžbu zajedno sa svim sastojcima za sva jela sumarno:
4 fileta, 60 ml kečapa, 2 lista salate, **3 somuna**, 10 ćevapa, 30 gr luka.

**Comment by emhuskic** [comment]
Funkcionalnost je dodana u novoj verziji SRS-a.
